version: "3.9"

x-restart-policy: &restart_policy
  restart: unless-stopped

# https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
# https://node-js.tistory.com/32

services:
  nginx:
    <<: *restart_policy
    container_name: nginx
    image: nginx:1.16.1-alpine
    volumes:
      - type: bind
        source: /var/log/nginx
        target: /mnt/log
      - type: bind
        source: ./config/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  nginx_exporter:
    <<: *restart_policy
    container_name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:0.7.0
    ports:
      - 9113:9113
    command: "-nginx.scrape-uri http://nginx/_/stub_status"
    depends_on:
      - nginx
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
